version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dataharries_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app_network
    restart: always

  redis:
    image: redis:7
    container_name: dataharries_redis
    networks:
      - app_network
    restart: always

  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001 --workers 2 --threads 2
    volumes:
      - static_volume:/app/staticfiles:rw
      - media_volume:/app/media:rw
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: dataharries_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge
