# Generated by Django 5.2 on 2025-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, default='No Title by User', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mspost',
            name='title',
            field=models.CharField(blank=True, default='No Title by Author', max_length=255, null=True),
        ),
    ]
