# Generated by Django 5.2 on 2025-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='mobile_no',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='profile_pic',
            field=models.ImageField(blank=True, default='faces/profile.png', null=True, upload_to='faces/'),
        ),
        migrations.AddField(
            model_name='userauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
