# Generated by Django 5.2 on 2025-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userauth_location_userauth_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauth',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'User'},
        ),
        migrations.AlterField(
            model_name='userauth',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
