# Generated by Django 5.2 on 2025-05-21 09:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_amount_alter_donation_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_session_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
