# Generated by Django 5.2 on 2025-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_stripe_session_url_alter_donation_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='stripe_session_url',
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
