# Generated by Django 5.2 on 2025-07-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacyterms', '0002_alter_privacypolicy_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='title',
        ),
        migrations.RemoveField(
            model_name='termsconditions',
            name='title',
        ),
        migrations.RemoveField(
            model_name='trustsafety',
            name='title',
        ),
    ]
